[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false

[profile.bsc]
chain_id = 56
gas_limit = 30000000

[profile.bsc-testnet]
chain_id = 97
gas_limit = 30000000

[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"
